#+TITLE: The Fediverse and Mastadon
* Social Media
** Why do people use it (Top 10 from Pew)
1. To stay in touch with what friends are doing (42%)
2. To stay up-to-date with news and current events (41%)
3. To fill up spare time (39%)
4. To find funny or entertaining content (37%)
5. General networking with other people (34%)
6. Because friends are already on them (33%)
7. To share photos or videos with others (32%)
8. To share my opinion (30%)
9. To research new products to buy (29%)
10. To meet new people (27%)
** Why people avoid it
- Find it a time waste. 
- Don't want to take the time to learn how.
- Not intertested in it. 
- Don't see any value in it.
- Concerned about their information/identity getting out.
- Privacy and advertising concerns. 
** Why do businesses use it
- Gaining traffic
- Interacting with your customers
- Increased sales
- Reputation management
- Marketing research
- Inexpensive
- The reach is global
- Save on advertising
- 2.82 Billion people worldwide on social media
* Silos
The silos are centralized monolithic servers that control all the data,  
identities, and access.  
- Facebook
- YouTube
- Instagram
- Twitter
- Google+
- Instagram
- Tumblr
- Pintrest
* Federated Alternatives

The fediverse is a collection of federated applications that use common  
protocols and decentralized servers. They are made up of free and open  
source software. I will be focusing mainly on Mastodon.

- Mastodon
- Pleroma
- GNU Social
- Gab
- Pixelfed
- PeerPx
- Peertube
- Funkwhale
- Friendica
- Diaspora
- Hubzilla
- Nextcloud
- Plume
- WriteFreely
- MissKey
- And many more every day
** Protocols
- ActivityPub ::
   This is the key to Mastodon and most of the current servers. This is why  
   the are all able to federate together. Possibly the last good thing to 
   come out of W3C before their anit-piracy controversy.  
- OStatus ::
   This was the beginning and got GNUSocial off the ground. But after the  
   wide adoption of AvtivityPub only Friendica and GNU Social still support  
   this.
- DFRN ::
   Distributed Friends and Relations Network protocol. Supported by 
   Friendica but I am not sure of another. 
- Diaspora Network ::
   This protocol is supported by Diaspora and Friendica. 
- XMPP ::
   This is messaging protocol. It is also federated and distributed. There  
   is no big central authority, and you can run your own server. Everyone  
   gets their own JID and with "transports" can even intereact between  
   non XMPP servers.
- Zot & Zot6 ::      
   This is used in Hubzilla. Communications are excrypted at both ends.
- Atom, Activity Streams, WebSub, Salmon, and WebFinger ::
   These where the start of many of these protocols. They choose to be  
   able to connect to these open protocols for social networking.   
** Microblogging
Most people know what blogging is. A blog site resembles a periodical magazine  
in that a specific topic or even a stream of consciousness it explored by an  
author and published daily, weekly, monthly, or perhaps with a little less  
disciplined schedule. Then there is Microblogging. This is what is most  
associated with Twitter. Short messages (originally 140 characters or less)  
are published in short periods of time sometimes many multiple times per day.  
The author may have an audience, like our current President. Or perhaps hopes  
to establish an audience of followers that engage such small blogs with  
reactive commentary, republishing, and sharing. Or by simply upvoting them.  
Twitter has shown this to be an effecive medium, and many people have bought  
into it either as consumers or content creators. As such, content creators  
have become influencers and even derived income from companies wanting them  
to mention, use, or otherwise display their wares. And to paraphrase the 
famous  George and Ira Gershwin "It's nice work if you can it!"
* Mastodon
Because Mastadon uses ActivityPub any other server that uses it can share data  
like toots or whatever each of them calls their posts. For instance, I an share  
a video on PeerTube, share and boost and comment on it from Mastadon and others  
who don't even have an account on PeerTube can see it, comment on it, follow it,  
and share it.  

Think of federation in the way you do eMail. You may have an account on Gmail..
and I have an account on HoTMaiL, and yet another person may have an account on  
their work's privately run Exchange server. But sending and receiving email between  
us is straight forward and we don't need accounts on each other's servers. 

Visually, to the end user, Mastodon looks like Twitter, or more specifically an  
interface called TweetDeck. However, it doesn't have to look that way, you can  
even use certain IRC clients to access your accounts.  

Most interfaces however, seem to be multicolumn and I will describe this based on  
the ones I have worked with.  

To start with, because Mastodon is a big furry elephant like thing rather than a  
bird, posts made are called "toots". I will pause while you snicker. If you choose  
to befriend someone you "follow" them. Where you connect is called an "instance".  
If you like someone's toot that is called a boost, which will cause it to be  
reposted to everyone who considers you a friend (your followers). 

Instances can and are run by anyone. One of the servers called "Pleroma" is made  
specifically to be lightweight enough that you can install it on a RaspberryPi.  
This is the major difference between the Fediverse and the Silos. Everyone  
can run their own instance if they choose to, or they can connect through free  
ones setup and maintained by other. A company could setup an instance for their  
employees only. A family can setup and instance for their own use. A club could  
be formed and charge membership. And they are so cheap and easy to setup and run  
no one "needs" to monetize. You can be a member on one or more instance, and  
if you want, you can move all your data from one instance to another. Instances  
tend to have a theme or general common interest. So you pick one that fits your  
interests.  

Normally there are 3 main columns or views. Home, local, and federated view. The  
home view contains all the toots from everyone you "follow" regardless of their  
instance. In addition to that, if someone you follow boosts a toot you will see  
that too. In the local view are all the toots from everyone on your instance.  
Of course, and any toot any of them have choosen to boost. Then comes the  
Federated view. Care to take a guess? Everyone on your instance, everyone they  
follow and everyone they follow etc. toots, and boosts. 

Federation happens, because once their is at least one person following another  
on a different instance, now the instances federate because of it. 

On the silos, someone you don't really know based on information you are not privy  
to makes decisions about what you can and can't see, say, and in what order you  
get to do so. You timelines are dictated by by algorithm and you are shown those  
things they have determined will generate them the most revenue by exposing you to  
advertisements.  Their business model dictates this. They are large with large  
servers that need large groups of maintainers with large salaries.

In the fediverse the low cost to run an instance allows people to do it without vast  
need to get income from it. Some people use things like Patreon and their open  
source alternatives like Liberapay.  

You can currate your views by blocking, or muting anyone you choose not to hear from  
for any reason you like. You can block a particular conversation you are in. You can  
even block or mute whole instances.  

Interestingly enough an instance can do the same thing. An instance can set rules as  
to what is acceptable speech, topics, and behaviors as well as what the repricussions  
for such infractions are. This may cause some controversy, but the ability to simply  
take all your data and move to another instance or create your own should negate any  
issue this causes. 

If you are interested there are instance finders, node lists and other helpful  
sites that you can start with. 
- Lets you pick an instnace from some criteria :: https://joinmastodon.org/ 
- Quickstart, choose lanugage and some criteria :: https://instances.social/
- Blog about software changes and general info :: https://blog.joinmastodon.org/  
- Place where you can follow people with similar interests :: https://communitywiki.org/trunk/
- How to setup a Mastodon instance :: https://tinyurl.com/y7bcwldf 
- How to setup a Pleroma instance  :: https://tinyurl.com/wtr3wrw
- News about the Fediverse and links and information on different services :: https://fediverse.party/
- Emacs interface into Mastodon :: https://github.com/jdenen/mastodon.el
- Vim interface into Mastodon :: https://github.com/mattn/vim-mastodon
- Electron interface into Mastodon :: https://github.com/h3poteto/whalebird-desktop

Or if you know of a specific instance (like if a friend tells you theirs) you can  
just go to it and if they are open to new users you can join. 
* Recent Influx
Free Speech has been a big reason for people leaving Twitter and Tumblr for Mastadon.  
The latest big move was due to one of India's Supreme Court lawyers (Sanjay Hegde)  
having his Twitter account suspended twice. Once for an image of August Landmesser,  
refusing to perform the Nazi salute and again for a poem that protested the hanging of  
two revolutionaries. 
- BBC News Article :: http://tiny.cc/hvhdgz

It is interesting that Free Speech is as common a reason for people to flock to the  
Fediverse as any other. However, the general bent of the Fediverse tends to lean more  
toward safe spaces and places to avoid abuseive treatment. There are plenty of tools  
available for moderation of both you own personal views of the network, as well as  
to those running instances to currate how those on their instance will experience it.  
This has met with some controversy in itself, as those wanting ultimate free speech  
and those who don't want to be insulted or have their beliefs challenged come to be 
at odds with one another.  This does make for some drama, but again, you are free  
to choose an instance that falls in line with your beliefs on these matters, even if  
that means you are in one that tries to be completely self contained. And if you 
find you are not happy where you are, you can move all your data, and everything to  
another instance. The tools are there that make it simple. 

- My Links :: http://bradleysmall.com/
- Read More :: https://wiki.freedombone.net/
 
